return function(Context)
    return function(page, window)
        local C = Context.Modules["ui/Components"]
        local controller = Context.Controllers.PlayerController
        local snapshot = Context.Services.PlayerService:Snapshot()
        C.Label(page, "PLAYER", 34, "title")
        C.Section(page, "Movement")
        C.NumberInput(page, "WalkSpeed", snapshot.walkSpeed, function(value)
            return controller:SetWalkSpeed(value)
        end)
        local walkToggle = C.Toggle(page, "Enable WalkSpeed Override", false, function(enabled)
            local ok, err = controller:EnableWalkSpeed(enabled)
            if ok == false then Context.Logger:Warn(err) end
        end)
        C.NumberInput(page, "JumpPower", snapshot.jumpPower, function(value)
            return controller:SetJumpPower(value)
        end)
        C.NumberInput(page, "JumpHeight", snapshot.jumpHeight, function(value)
            return controller:SetJumpHeight(value)
        end)
        C.NumberInput(page, "Gravity", snapshot.gravity, function(value)
            return controller:SetGravity(value)
        end)
        local jumpToggle = C.Toggle(page, "Infinite Jump", false, function(enabled)
            controller:EnableInfiniteJump(enabled)
        end)
        local noclipToggle = C.Toggle(page, "Noclip", false, function(enabled)
            controller:EnableNoclip(enabled)
        end)
        local freezeToggle = C.Toggle(page, "Freeze", false, function(enabled)
            local ok, err = controller:EnableFreeze(enabled)
            if ok == false then Context.Logger:Warn(err) end
        end)
        local reapplyToggle = C.Toggle(page, "Reapply After Respawn", controller.ReapplyAfterRespawn, function(enabled)
            controller:SetReapply(enabled)
        end)
        C.Button(page, "TP TO BASE", function()
            Context.Controllers.TeleportController:ToBase()
        end, C.Theme.accent)
        C.Button(page, "RESET MOVEMENT", function()
            controller:ResetMovement()
        end, C.Theme.danger)
        local speedPower = C.Label(page, "SpeedPower: UNKNOWN", 58, "mono")
        local function refreshToggles()
            walkToggle:Set(Context.State:Get("walkSpeedEnabled", false), true)
            jumpToggle:Set(Context.State:Get("infiniteJumpEnabled", false), true)
            noclipToggle:Set(Context.State:Get("noclipEnabled", false), true)
            freezeToggle:Set(Context.State:Get("freezeEnabled", false), true)
            reapplyToggle:Set(Context.State:Get("reapplyPlayerSettings", true), true)
        end
        window:Connect(Context.State.Changed, refreshToggles)
        refreshToggles()
        window:OnPulse(function()
            local details = Context.Services.PlayerService:ReadSpeedPower()
            speedPower.Text = "SpeedPower: " .. tostring(details.value or "UNKNOWN")
                .. "\nEqualised: " .. tostring(details.equalised or "UNKNOWN")
                .. "  Minimum: " .. tostring(details.minimum or "UNKNOWN")
        end)
    end
end
